Junjut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
]

account/urls.py
from os import name
from . import views
from django.urls import path


app_name = 'account'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('reset-password/<str:url>/', views.reset_password, name='reset_password'),
    path('admin/', views.admin, name='admin'),
]

home/urls.py
from os import name
from . import views
from django.urls import path


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('verified/<str:url>/', views.verified, name='verified'),
    path('login/', views.login, name='login'),
    path('OTPP/', views.OTPP, name='OTPP'),
    path('notification-verify-email/', views.notif_verify_email, name='notif_verify_email'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

account/views.py
from modules import *
globals().update(import_modules('account.views', globals()))


# Create your views here.
@never_cache
@require_http_methods(['GET', 'POST'])
def dashboard(request):
    db_pre_process(request)
    session_id = request.session.get('session_id', '')
    if request.method == 'POST' and db_session_id(session_id):
        data = request.POST
        if 'log_out' in data:
            db_log_out(session_id)
            return HttpResponseRedirect(reverse('home:login'))
        return HttpResponseRedirect(reverse('home:login'))
    if db_session_id(session_id):
        return render(request, 'account/dashboard.html', dashboard_vars(session_id))
    return HttpResponseRedirect(reverse('home:login'))


@never_cache
@require_http_methods(['GET', 'POST'])
def reset_password(request, url):
    db_pre_process(request)
    if request.method == 'POST' and allowed_reset_pass_url(url):
        data = request.POST
        if 'password' in data:
            password = data['password']
            update_password(url, password)
            return HttpResponseRedirect(reverse('home:login'))
        return HttpResponseRedirect(reverse('home:login'))
    if allowed_reset_pass_url(url):
        return render(request, 'account/reset_password.html', reset_password_vars(url))
    return HttpResponseRedirect(reverse('home:login'))


@never_cache
@require_http_methods(['GET', 'POST'])
def admin(request):
    db_pre_process(request)
    session_id = request.session.get('session_id', '')
    if request.method == 'POST' and db_session_id(session_id):
        permissions = db_permissions(session_id)
        if permissions.get('admin') == 'True':
            data = request.POST
            if 'example' in data:
                pass
                return HttpResponseRedirect(reverse('account:admin'))
        return HttpResponseRedirect(reverse('home:login'))
    if db_session_id(session_id):
        permissions = db_permissions(session_id)
        if permissions.get('admin') == 'True':
            return render(request, 'account/admin.html', admin_vars())
    return HttpResponseRedirect(reverse('home:login'))

home/views.py
from modules import *
globals().update(import_modules('home.views', globals()))


# Create your views here.
@never_cache
@require_http_methods(['GET'])
def index(request):
    db_pre_process(request)
    return render(request, 'home/index.html', index_vars())


@csp_exempt
@never_cache
@require_http_methods(['GET'])
def notif_verify_email(request):
    db_pre_process(request)
    return render(request, 'home/notif_verify_email.html', notif_verify_email_vars())


@csp_exempt
@never_cache
@require_http_methods(['GET'])
def terms_of_service(request):
    db_pre_process(request)
    return render(request, 'home/terms_of_service.html', terms_of_service_vars())


@csp_exempt
@never_cache
@require_http_methods(['GET'])
def privacy_policy(request):
    db_pre_process(request)
    return render(request, 'home/privacy_policy.html', privacy_policy_vars())


@never_cache
@require_http_methods(['GET'])
def verified(request, url):
    db_pre_process(request)
    db_verify_email(url)
    return HttpResponseRedirect(reverse('home:login'))


@never_cache
@require_http_methods(['GET', 'POST'])
def OTPP(request):
    db_pre_process(request)
    OTPP_session_id = request.session.get('OTPP_session_id', '')
    if request.method == 'POST' and db_OTPP_session_id(OTPP_session_id):
        data = request.POST
        if 'OTPP' in data:
            OTPP = data['OTPP']
            if db_verify_OTPP(OTPP_session_id, OTPP):
                request.session['session_id'] = db_verify_OTPP(OTPP_session_id, OTPP, update = True)
                return HttpResponseRedirect(reverse('account:dashboard'))
            db_verify_OTPP(OTPP_session_id, OTPP, unverified = True)
            return HttpResponseRedirect(reverse('home:login'))
        return HttpResponseRedirect(reverse('home:login'))
    if db_OTPP_session_id(OTPP_session_id):
        return render(request, 'home/OTPP.html', OTPP_vars(OTPP_session_id))
    return HttpResponseRedirect(reverse('home:login'))


@never_cache
@require_http_methods(['GET', 'POST'])
def login(request):
    db_pre_process(request)
    TOSAPP = request.session.get('TOSAPP', False)
    if request.method == 'POST':
        data = request.POST
        if 'TOSAPP' in data:
            request.session['TOSAPP'] = True
            return HttpResponseRedirect(reverse('home:login'))
        if all (key in data for key in ('forgot_password', 'email')) and TOSAPP:
            if data['email']:
                email = data['email']
                db_forgot_pass(email)
            return HttpResponseRedirect(reverse('home:login'))
        if all (key in data for key in ('email', 'password')) and TOSAPP:
            if data['email'] and data['password']:
                email = data['email']
                password = data['password']
                if db_login(email, password):
                    request.session.cycle_key()
                    request.session['OTPP_session_id'] = db_send_OTPP(email)
                    return HttpResponseRedirect(reverse('home:OTPP'))
                if db_account(email):
                    return HttpResponseRedirect(reverse('home:login'))
                if db_signed_up(email) == False:
                    url = secret_url()
                    if validate_email(email, url) == True:
                        db_sign_up(email, password, url)
                return HttpResponseRedirect(reverse('home:notif_verify_email'))
            return HttpResponseRedirect(reverse('home:login'))
        return HttpResponseRedirect(reverse('home:login'))
    if TOSAPP:
        return render(request, 'home/login.html', login_vars())
    return render(request, 'home/TOSAPP.html', TOSAPP_vars())

home/templates/home/OTPP.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>OTPP</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="https://junjut.github.io/home/login_OTPP/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/css/util.css">
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w" action="" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-32">
						One-time Passphrase
					</span>
					
					<span class="txt1 p-b-11">
						OTPP
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate = "OTPP is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="OTPP">
						<span class="focus-input100"></span>
					</div>
					
					<div class="flex-sb-m w-full p-b-48">
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/bootstrap/js/popper.js"></script>
	<script src="https://junjut.github.io/home/login_OTPP/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/daterangepicker/moment.min.js"></script>
	<script src="https://junjut.github.io/home/login_OTPP/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/js/main.js"></script>

</body>
</html>

home/templates/home/TOSAPP.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  
  <link rel="apple-touch-icon" sizes="180x180" href="https://junjut.github.io/home/TOSAPP/assets/apple-icon-180x180.png">

  <link href="" rel="stylesheet">

  <script src="https://junjut.github.io/home/TOSAPP/custom.js"></script>

  <title>Junjut</title>

<link href="https://junjut.github.io/home/TOSAPP/main.550dcf66.css" rel="stylesheet"></head>

<body> <!-- Add your content of header -->


<!-- Add your site or app content here -->
  <div class="hero-full-container background-image-container white-text-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1>JUNJUT/h1>
          <p>By continuing, I acknowledge that I have read, and do hereby accept the <a href="{% url 'home:terms_of_service' %}">Terms of Service</a> and <a href="{% url 'home:privacy_policy' %}">Privacy Policy</a> as provided by Junjut.</p>
          <br>
          <form id="TOSAPP_form" action="{% url 'home:login' %}" method="POST">
            {% csrf_token %}
            <a href="" id="TOSAPP" class="btn btn-default btn-lg" title="">Continue</a>
          </form>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Junjut</title>
    <link href="https://fonts.googleapis.com/css?family=Heebo:400,700|Oxygen:700" rel="stylesheet">
    <link rel="stylesheet" href="https://junjut.github.io/home/index/dist/css/style.css">
    <script src="https://unpkg.com/scrollreveal@4.0.5/dist/scrollreveal.min.js"></script>
</head>
<body class="is-boxed has-animations">
    <div class="body-wrap boxed-container">
        <header class="site-header text-light">
            <div class="container">
                <div class="site-header-inner">
                    <div class="brand header-brand">
                        <h1 class="m-0">
                            <a href="#">
								<img class="header-logo-image" src="https://junjut.github.io/home/index/dist/images/logo.svg" alt="Logo">
                            </a>
                        </h1>
                    </div>
                </div>
            </div>
        </header>

        <main>
            <section class="hero text-center text-light">
				<div class="hero-bg"></div>
				<div class="hero-particles-container">
					<canvas id="hero-particles"></canvas>
				</div>
                <div class="container-sm">
                    <div class="hero-inner">
						<div class="hero-copy">
	                        <h1 class="hero-title mt-0">Junjut's Finest Real Estate</h1>
	                        <p class="hero-paragraph">Our landing page template works on all devices, so you only have to set it up once, and get beautiful results forever.</p>
	                        <div class="hero-cta">
								<a class="button button-primary button-wide-mobile" href="{% url 'home:login' %}">Sign Up Now</a>
							</div>
						</div>
						<div class="mockup-container">
							<div class="mockup-bg">
								<img src="https://junjut.github.io/home/index/dist/images/iphone-hero-bg.svg" alt="iPhone illustration">
							</div>
							<img class="device-mockup" src="https://junjut.github.io/home/index/dist/images/iphone-hero.png" alt="iPhone Hero">
						</div>
                    </div>
                </div>
            </section>

			<section class="features-extended section">
                <div class="features-extended-inner section-inner">
					<div class="features-extended-wrap">
						<div class="container">
							<div class="feature-extended">
								<div class="feature-extended-image">
									<div class="mockup-bg">
										<img src="https://junjut.github.io/home/index/dist/images/iphone-feature-bg-01.svg" alt="iPhone Feature 01 illustration">
									</div>
									<img class="device-mockup is-revealing" src="https://junjut.github.io/home/index/dist/images/iphone-feature-01.png" alt="iPhone Feature 01">
								</div>
								<div class="feature-extended-body is-revealing">
									<h3 class="mt-0 mb-16">Amazing features, coming soon.</h3>
									<p class="m-0">Quam quisque id diam vel quam elementum pulvinar. Ut etiam sit amet nisl purus in mollis nunc. Odio morbi quis commodo odio aenean sed adipiscing diam donec.</p>
								</div>
							</div>
							<div class="feature-extended">
								<div class="feature-extended-image">
									<div class="mockup-bg">
										<img src="https://junjut.github.io/home/index/dist/images/iphone-feature-bg-02.svg" alt="iPhone Feature 02 illustration">
									</div>
									<img class="device-mockup is-revealing" src="https://junjut.github.io/home/index/dist/images/iphone-feature-02.png" alt="iPhone Feature 02">
								</div>
								<div class="feature-extended-body is-revealing">
									<h3 class="mt-0 mb-16">Amazing features, coming soon.</h3>
									<p class="m-0">Quam quisque id diam vel quam elementum pulvinar. Ut etiam sit amet nisl purus in mollis nunc. Odio morbi quis commodo odio aenean sed adipiscing diam donec.</p>
								</div>
							</div>
							<div class="feature-extended">
								<div class="feature-extended-image">
									<div class="mockup-bg">
										<img src="https://junjut.github.io/home/index/dist/images/iphone-feature-bg-03.svg" alt="iPhone Feature 03 illustration">
									</div>
									<img class="device-mockup is-revealing" src="https://junjut.github.io/home/index/dist/images/iphone-feature-03.png" alt="iPhone Feature 03">
								</div>
								<div class="feature-extended-body is-revealing">
									<h3 class="mt-0 mb-16">Amazing features, coming soon.</h3>
									<p class="m-0">Quam quisque id diam vel quam elementum pulvinar. Ut etiam sit amet nisl purus in mollis nunc. Odio morbi quis commodo odio aenean sed adipiscing diam donec.</p>
								</div>
							</div>
							<div class="feature-extended">
								<div class="feature-extended-image">
									<div class="mockup-bg">
										<img src="https://junjut.github.io/home/index/dist/images/iphone-feature-bg-04.svg" alt="iPhone Feature 04 illustration">
									</div>
									<img class="device-mockup is-revealing" src="https://junjut.github.io/home/index/dist/images/iphone-feature-04.png" alt="iPhone Feature 04">
								</div>
								<div class="feature-extended-body is-revealing">
									<h3 class="mt-0 mb-16">Amazing features, coming soon.</h3>
									<p class="m-0">Quam quisque id diam vel quam elementum pulvinar. Ut etiam sit amet nisl purus in mollis nunc. Odio morbi quis commodo odio aenean sed adipiscing diam donec.</p>
								</div>
							</div>
						</div>
					</div>
                </div>
            </section>
        </main>

		<footer class="site-footer">
			<div class="footer-particles-container">
				<canvas id="footer-particles"></canvas>
			</div>
			<div class="site-footer-top">
				<section class="cta section text-light">
					<div class="container-sm">
						<div class="cta-inner section-inner">
							<div class="cta-header text-center">
								<h2 class="section-title mt-0">Stay in the know</h2>
								<p class="section-paragraph">Lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation.</p>
								<div class="cta-cta">
									<a class="button button-primary button-wide-mobile" href="{% url 'home:login' %}">Let Me In</a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
			<div class="site-footer-bottom">
				<div class="container">
					<div class="site-footer-inner">
						<div class="brand footer-brand">
							<a href="#">
								<img src="https://junjut.github.io/home/index/dist/images/logo.svg" alt="Venus logo">
							</a>
						</div>
						<ul class="footer-links list-reset">
							<li>
								<a href="#">Contact</a>
							</li>
							<li>
								<a href="#">About us</a>
							</li>
							<li>
								<a href="#">FAQ's</a>
							</li>
							<li>
								<a href="#">Support</a>
							</li>
						</ul>
						<ul class="footer-social-links list-reset">
							<li>
								<a href="#">
									<span class="screen-reader-text">Facebook</span>
									<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
										<path d="M6.023 16L6 9H3V6h3V4c0-2.7 1.672-4 4.08-4 1.153 0 2.144.086 2.433.124v2.821h-1.67c-1.31 0-1.563.623-1.563 1.536V6H13l-1 3H9.28v7H6.023z" fill="#FFF"/>
									</svg>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="screen-reader-text">Twitter</span>
									<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
										<path d="M16 3c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4C.7 7.7 1.8 9 3.3 9.3c-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H0c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4C15 4.3 15.6 3.7 16 3z" fill="#FFF"/>
									</svg>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="screen-reader-text">Google</span>
									<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
										<path d="M7.9 7v2.4H12c-.2 1-1.2 3-4 3-2.4 0-4.3-2-4.3-4.4 0-2.4 2-4.4 4.3-4.4 1.4 0 2.3.6 2.8 1.1l1.9-1.8C11.5 1.7 9.9 1 8 1 4.1 1 1 4.1 1 8s3.1 7 7 7c4 0 6.7-2.8 6.7-6.8 0-.5 0-.8-.1-1.2H7.9z" fill="#FFF"/>
									</svg>
								</a>
							</li>
						</ul>
						<div class="footer-copyright">&copy; 2021 Junjut, all rights reserved</div>
					</div>
				</div>
			</div>
        </footer>
    </div>

    <script src="https://junjut.github.io/home/index/dist/js/main.min.js"></script>
</body>
</html>

home/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="https://junjut.github.io/home/login_OTPP/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/css/util.css">
	<link rel="stylesheet" type="text/css" href="https://junjut.github.io/home/login_OTPP/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				
				<form id="forgotform" action="{% url 'home:login' %}" method="POST">
					{% csrf_token %}
					<input type="hidden" name="forgot_password" value="">
				</form>

				<form class="login100-form validate-form flex-sb flex-w" action="{% url 'home:login' %}" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-32">
						Account Login
					</span>

					<span class="txt1 p-b-11">
						Email
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Email is required">
						<input class="input100" type="email" name="email" id="email">
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Password
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<span class="focus-input100"></span>
					</div>
					
					<div class="flex-sb-m w-full p-b-48">
						<div class="contact100-form-checkbox">
							
						</div>

						<div>
							<a href="" id="forgotlink" class="txt3">
								Forgot Password?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/js/custom.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/bootstrap/js/popper.js"></script>
	<script src="https://junjut.github.io/home/login_OTPP/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/daterangepicker/moment.min.js"></script>
	<script src="https://junjut.github.io/home/login_OTPP/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="https://junjut.github.io/home/login_OTPP/js/main.js"></script>

</body>
</html>